// Generated by psc version 0.6.2
var PS = PS || {};
PS.Prelude = (function () {
    "use strict";
    function cons(e) {  return function(l) {    return [e].concat(l);  };};
    var $colon = cons;
    var $dollar = function (f) {
        return function (x) {
            return f(x);
        };
    };
    return {
        "$": $dollar, 
        ":": $colon, 
        cons: cons
    };
})();
var PS = PS || {};
PS.Thermite_Html = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    
  function props(ps) {
    var result = {};

    for (var i = 0; i < ps.length; i++) {
      result[ps[i][0]] = ps[i][1];
    }

    return result;
  }
  ;
    
  function text(s) {
    return s;
  }
  ;
    
  function createElement(name) {
    return function(props) {
      return function(children) {
        return React.createElement(name, props, children);
      };
    };
  }
  ;
    
  function onChange(context) {
    return function (f) {
      return ["onChange", function(e) {
        context.performAction(f(e.target.value));
      }];
    };
  }
  ;
    return {
        createElement: createElement, 
        onChange: onChange, 
        props: props, 
        text: text
    };
})();
var PS = PS || {};
PS.Data_Maybe = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    function Nothing() {

    };
    Nothing.value = new Nothing();
    function Just(value0) {
        this.value0 = value0;
    };
    Just.create = function (value0) {
        return new Just(value0);
    };
    return {
        Just: Just, 
        Nothing: Nothing
    };
})();
var PS = PS || {};
PS.Thermite = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var Spec = {
        create: function (value) {
            return value;
        }
    };
    
  function createClassImpl(spec) {
    return React.createClass({
      getInitialState: function() {
        return spec.initialState;
      },
      performAction: function(action) {
        var self = this;
        spec.performAction(self.state)(action)(function(state) {
          return function() {
            self.setState(state);
          };
        })();
      },
      render: function() {
        return spec.render(this)(this.state);
      }
    }); 
  }
  ;
    
  function render(component) {
    return function() {
      React.render(React.createElement(component, null), document.body);
    };
  }
  ;
    var createClass = function (_62) {
        return createClassImpl(_62);
    };
    return {
        Spec: Spec, 
        createClass: createClass, 
        render: render
    };
})();
var PS = PS || {};
PS.Main = (function () {
    "use strict";
    var Thermite_Html = PS.Thermite_Html;
    var Thermite = PS.Thermite;
    var Prelude = PS.Prelude;
    var Data_Maybe = PS.Data_Maybe;
    function State(value0) {
        this.value0 = value0;
    };
    State.create = function (value0) {
        return new State(value0);
    };
    function TextChanged(value0) {
        this.value0 = value0;
    };
    TextChanged.create = function (value0) {
        return new TextChanged(value0);
    };
    var render = function (_63) {
        return function (_64) {
            var welcome = Thermite_Html.createElement("p")(Thermite_Html.props([  ]))([ Thermite_Html.text("What is your name? "), Thermite_Html.createElement("input")(Thermite_Html.props([ Thermite_Html.onChange(_63)(TextChanged.create) ]))([  ]) ]);
            var response = function (_68) {
                if (_68 === "") {
                    return [  ];
                };
                return [ Thermite_Html.createElement("p")(Thermite_Html.props([  ]))([ Thermite_Html.text("Hello, "), Thermite_Html.text(_68) ]) ];
            };
            return Thermite_Html.createElement("p")(Thermite_Html.props([  ]))(Prelude[":"](welcome)(response(_64.value0)));
        };
    };
    var performAction = function (_65) {
        return function (_66) {
            return function (_67) {
                return _67(new State(_66.value0));
            };
        };
    };
    var initialState = new State("");
    var spec = {
        initialState: initialState, 
        setup: Data_Maybe.Nothing.value, 
        performAction: performAction, 
        render: render
    };
    var main = (function () {
        var component = Thermite.createClass(spec);
        return Thermite.render(component);
    })();
    return {
        main: main
    };
})();
PS.Main.main();
